"use client"

import Image from "next/image"
import Link from "next/link"
import { useState } from "react"
import LandingPricing from "./landing-pricing"

const journey = [
  ["01 / RESERVA", "O cliente escolhe.", "Um link direto para marcar horário a qualquer momento."],
  ["02 / AGENDA", "A equipe acompanha.", "Horários e profissionais organizados no dia."],
  ["03 / ATENDIMENTO", "O contexto aparece.", "Serviços, preferências e histórico à mão."],
  ["04 / GESTÃO", "Os números fecham.", "Financeiro e operação em uma leitura clara."],
]

export default function LandingRedesign() {
  const [mobileOpen, setMobileOpen] = useState(false)
  return <div className="hb-landing min-h-screen bg-[#F6F5F2] text-[#242321] [font-family:var(--font-inter),Arial,sans-serif]">
    <a href="#conteudo" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-white focus:p-3">Pular para o conteúdo</a>
    <header className="sticky top-0 z-30 bg-[#232220] text-white">
      <nav className="mx-auto flex h-[72px] max-w-[1320px] items-center justify-between gap-6 px-5 sm:px-8 lg:px-12" aria-label="Navegação principal">
        <Link href="/" aria-label="HeadBarber, início" className="inline-flex shrink-0 items-center"><Image src="/brand/headbarber_logo_duas_cores_com_texto_transparente.png" alt="HeadBarber" width={1083} height={795} className="h-[55px] w-auto object-contain" priority /></Link>
        <div className="hidden items-center gap-8 md:flex"><a href="#como-funciona" className="text-sm text-[#dedbd5] hover:text-white">Como funciona</a><a href="#precos" className="text-sm text-[#dedbd5] hover:text-white">Preços</a><Link href="/demo" className="text-sm text-[#dedbd5] hover:text-white">Demonstração</Link><Link href="/login" className="inline-flex min-h-11 items-center bg-[#C79A4A] px-5 text-sm font-semibold text-[#211b12] hover:bg-[#d7ae66]">Começar agora <span className="ml-3" aria-hidden="true">→</span></Link></div>
        <button type="button" className="flex h-11 w-11 items-center justify-center border border-white/30 md:hidden" aria-label={mobileOpen ? "Fechar menu" : "Abrir menu"} aria-expanded={mobileOpen} aria-controls="landing-mobile-nav" onClick={() => setMobileOpen(open => !open)}><span aria-hidden="true" className="text-2xl">{mobileOpen ? "×" : "☰"}</span></button>
      </nav>
      {mobileOpen && <div id="landing-mobile-nav" className="grid gap-1 border-t border-white/15 px-5 pb-5 pt-3 text-sm md:hidden"><a href="#como-funciona" onClick={() => setMobileOpen(false)} className="py-3">Como funciona</a><a href="#precos" onClick={() => setMobileOpen(false)} className="py-3">Preços</a><Link href="/demo" onClick={() => setMobileOpen(false)} className="py-3">Demonstração</Link><Link href="/login" onClick={() => setMobileOpen(false)} className="mt-2 bg-[#C79A4A] px-5 py-3 text-center font-semibold text-[#211b12]">Começar agora</Link></div>}
    </header>
    <main id="conteudo">
      <section className="grid bg-[#232220] text-white lg:min-h-[570px] lg:grid-cols-[48%_52%]">
        <div className="mx-auto flex w-full max-w-[650px] flex-col justify-center px-5 py-14 sm:px-8 lg:ml-auto lg:px-12 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d6a85b]">Gestão para barbearias</p><h1 className="mt-7 max-w-[620px] text-balance [font-family:var(--font-montserrat),Arial,sans-serif] text-[clamp(2.8rem,4.7vw,4.9rem)] font-bold leading-[1.05] tracking-[-.055em]">O próximo corte começa com a casa em ordem.</h1><p className="mt-6 max-w-[480px] text-pretty text-base leading-relaxed text-[#d5d1c9] sm:text-lg">Agendamento, atendimento e gestão no mesmo ritmo da sua barbearia.</p><div className="mt-9 flex flex-wrap items-center gap-x-6 gap-y-4"><Link href="/login" className="inline-flex min-h-12 items-center bg-[#C79A4A] px-6 text-sm font-semibold text-[#211b12] hover:bg-[#d7ae66]">Organizar minha barbearia <span aria-hidden="true" className="ml-3">→</span></Link><Link href="/demo" className="text-sm font-semibold text-[#e6be78] underline underline-offset-4 hover:text-white">Ver demonstração</Link></div></div>
        <div className="relative min-h-[290px] lg:min-h-full"><Image src="/brand/barbershop-hero.png" alt="Barbeiro atendendo um cliente na cadeira" fill priority sizes="(max-width: 1024px) 100vw, 52vw" className="object-cover object-[65%_center]" /><div className="absolute inset-0 bg-[#201d18]/10" /><p className="absolute bottom-5 right-5 bg-[#211f1bd9] px-3 py-2 text-[10px] font-semibold uppercase tracking-[.12em] text-white">Para quem vive a rotina da barbearia</p></div>
      </section>
      <section id="como-funciona" className="scroll-mt-20 bg-white py-16 sm:py-20"><div className="mx-auto max-w-[1200px] px-5 sm:px-8"><p className="text-xs font-bold uppercase tracking-[.17em] text-[#986f2e]">Um dia, sem atrito</p><h2 className="mt-3 [font-family:var(--font-montserrat),Arial,sans-serif] text-[clamp(2rem,3vw,3rem)] font-semibold tracking-[-.045em]">Da reserva ao fechamento.</h2><div className="mt-9 grid border-y border-[#d9d4cb] sm:grid-cols-2 lg:grid-cols-4">{journey.map(([number, title, description]) => <Link href="/demo" key={number} className="group border-b border-[#d9d4cb] py-6 sm:border-r sm:px-5 lg:border-b-0 first:pl-0 last:border-r-0"><span className="text-[11px] font-bold uppercase tracking-[.14em] text-[#986f2e]">{number}</span><h3 className="mt-8 [font-family:var(--font-montserrat),Arial,sans-serif] text-lg font-semibold tracking-tight group-hover:text-[#986f2e]">{title}</h3><p className="mt-2 max-w-[230px] text-sm leading-relaxed text-[#625f59]">{description}</p></Link>)}</div></div></section>
      <section id="recursos" className="bg-[#E9E6DF] py-16 sm:py-20"><div className="mx-auto grid max-w-[1200px] items-center gap-9 px-5 sm:px-8 lg:grid-cols-[.65fr_1.35fr] lg:gap-14"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#986f2e]">Por dentro do produto</p><h2 className="mt-4 max-w-[350px] text-balance [font-family:var(--font-montserrat),Arial,sans-serif] text-[clamp(2rem,3vw,3rem)] font-semibold leading-[1.1] tracking-[-.045em]">Uma mesa de trabalho para o dia real.</h2><p className="mt-5 max-w-[350px] text-sm leading-relaxed text-[#625f59]">Veja os próximos atendimentos, a equipe e os números que importam, sem perder o foco no trabalho.</p><Link href="/demo" className="mt-6 inline-flex min-h-11 items-center font-semibold text-[#765623] underline underline-offset-4">Explorar o produto <span className="ml-2" aria-hidden="true">→</span></Link></div><div className="overflow-hidden border border-[#d4cec2] bg-white shadow-[0_16px_40px_#2423211a]"><Image src="/brand/product-overview-redesign.png" alt="Visão geral do HeadBarber com atendimentos do dia" width={1280} height={800} sizes="(max-width: 1024px) 100vw, 700px" className="h-auto w-full" /></div></div></section>
      <LandingPricing />
      <section aria-label="Parceiro oficial" className="bg-[#F6F5F2] py-14 sm:py-20"><div className="mx-auto flex max-w-[1200px] flex-col items-start justify-between gap-7 px-5 sm:px-8 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.17em] text-[#986f2e]">Parceiro oficial</p><h2 className="mt-3 [font-family:var(--font-montserrat),Arial,sans-serif] text-2xl font-semibold tracking-[-.04em] sm:text-3xl">Uma parceria que vem da barbearia.</h2><p className="mt-3 text-sm text-[#625f59]">A Hoffmann&apos;s Barber faz parte da história do HeadBarber.</p></div><Image src="/brand/partners/hoffmanns-barber.png" alt="Hoffmann's Barber" width={3817} height={2176} className="h-auto w-52 mix-blend-multiply" /></div></section>
    </main>
    <footer className="bg-[#20201f] py-9 text-[#dedbd5]"><div className="mx-auto flex max-w-[1200px] flex-col justify-between gap-5 px-5 text-sm sm:px-8 md:flex-row"><span>© {new Date().getFullYear()} HeadBarber.</span><div className="flex flex-wrap gap-5"><a href="#como-funciona">Como funciona</a><a href="#precos">Preços</a><Link href="/demo">Demonstração</Link><Link href="/login">Entrar</Link></div></div></footer>
  </div>
}
